import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtemp, mkdir } from 'node:fs/promises';
import { DecisionMemory } from '../packages/decision-memory/src/index.js';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';

const root = path.resolve(new URL('..', import.meta.url).pathname);
const temp = await mkdtemp(path.join(os.tmpdir(), 'agent-work-os-acceptance-'));
const workspace = path.join(temp, 'workspace');
await mkdir(workspace);
const memory = await DecisionMemory.init(workspace, 'acceptance/repository');
const decision = await memory.log({ claim:'replay proof', choice:'keep verified evidence', rationale:'synthetic acceptance fixture', source:'test://acceptance', sourceHash:'fixture-sha256-001', actor:'acceptance', verification:'verified', affectedPaths:['src/test.js'] });
const port = 18787 + Math.floor(Math.random()*500);
const env = { ...process.env, AGENT_WORK_OS_HOST:'127.0.0.1', AGENT_WORK_OS_PORT:String(port), AGENT_WORK_OS_TOKEN:'acceptance-token', AGENT_WORK_OS_STATE_PATH:path.join(temp,'state.json'), AGENT_WORK_OS_SERVER_URL:`ws://127.0.0.1:${port}/ws`, AGENT_WORK_OS_HOME:path.join(temp,'daemon-home'), AGENT_WORK_OS_MACHINE_NAME:'acceptance-machine', AGENT_WORK_OS_ENABLE_ECHO:'true' };
const children = [];
function start(args){const child=spawn(process.execPath,args,{cwd:root,env,stdio:['ignore','pipe','pipe']});children.push(child);child.stdout.on('data',d=>process.stdout.write(d));child.stderr.on('data',d=>process.stderr.write(d));return child;}
start(['services/control-api/src/index.js']);
await waitFor(async()=> (await fetch(`http://127.0.0.1:${port}/health`)).ok, 8000, 'api health');
let daemon = start(['runtime/daemon/src/index.js']);
const machine = await waitFor(async()=>{const s=await (await fetch(`http://127.0.0.1:${port}/api/state`)).json();return s.machines.find(m=>m.name==='acceptance-machine'&&m.status==='online');},8000,'daemon registration');
const create = await fetch(`http://127.0.0.1:${port}/api/sessions`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({machineId:machine.id,cwd:workspace,agent:'echo',prompt:'acceptance'})});
assert.equal(create.status,201);const session=await create.json();
let completed = await waitFor(async()=>{const s=await (await fetch(`http://127.0.0.1:${port}/api/sessions/${session.id}`)).json();return s.status==='completed'?s:null;},8000,'first echo turn');
assert.ok(completed.messages.some(m=>m.text==='Echo: acceptance'));
const follow = await fetch(`http://127.0.0.1:${port}/api/sessions/${session.id}/messages`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:'second'})}); assert.equal(follow.status,202);
completed = await waitFor(async()=>{const s=await (await fetch(`http://127.0.0.1:${port}/api/sessions/${session.id}`)).json();return s.messages.some(m=>m.text==='Echo: second')?s:null;},8000,'follow-up echo turn');
assert.equal(completed.nativeSessionId,`echo-${session.id}`);
const snapshot = await memory.handoff({ fromSessionId: session.id, nativeThreadId: completed.nativeSessionId, machineId: machine.id, goal:'new-session proof', lastActions:['first session complete'], changedFiles:['src/test.js'], checks:['echo pass'] });
// Verify real local daemon restart, not just a fresh DecisionMemory object.
daemon.kill('SIGTERM');
await waitFor(async()=>{const s=await (await fetch(`http://127.0.0.1:${port}/api/state`)).json();return s.machines.find(m=>m.id===machine.id&&m.status==='offline');},8000,'daemon shutdown');
daemon = start(['runtime/daemon/src/index.js']);
await waitFor(async()=>{const s=await (await fetch(`http://127.0.0.1:${port}/api/state`)).json();return s.machines.find(m=>m.id===machine.id&&m.status==='online');},8000,'daemon restart');
const newSessionResponse = await fetch(`http://127.0.0.1:${port}/api/sessions`, { method:'POST', headers:{'content-type':'application/json'}, body: JSON.stringify({ machineId:machine.id, cwd:workspace, agent:'echo', prompt:'fresh session', handoffId:snapshot.id, brainMode:'verified-context' }) });
assert.equal(newSessionResponse.status, 201);
const fresh = await newSessionResponse.json();
const recalled = await waitFor(async()=>{ const s=await (await fetch(`http://127.0.0.1:${port}/api/sessions/${fresh.id}`)).json();return s.status==='completed' ? s : null; },8000,'fresh-session handoff');
const proofEvent = recalled.events.find(e=>e.kind==='memory.proof');
assert.ok(proofEvent, 'daemon emitted a pre-agent persisted recall proof');
assert.equal(proofEvent.fromSessionId, session.id);
assert.equal(proofEvent.toSessionId, fresh.id);
assert.equal(proofEvent.decisionRefs[0].id, decision.id);
assert.equal(proofEvent.decisionRefs[0].contentHash, decision.contentHash);
assert.equal(proofEvent.decisionRefs[0].sourceHash, decision.provenance.sourceHash);
assert.ok(recalled.events.findIndex(e=>e.kind==='memory.proof') < recalled.events.findIndex(e=>e.kind==='status' && e.status==='running'));
const contextEvent = recalled.events.find(e=>e.kind==='memory.context');
assert.ok(contextEvent, 'daemon prepared explicit verified Brain context');
assert.equal(contextEvent.decisionCount, 1);
assert.ok(recalled.events.findIndex(e=>e.kind==='memory.context') < recalled.events.findIndex(e=>e.kind==='status' && e.status==='running'));
const brainEcho = recalled.messages.find(m=>m.role==='assistant' && m.text.includes('AGENT WORK OS SHARED BRAIN'));
assert.ok(brainEcho, 'adapter received shared Brain context');
assert.match(brainEcho.text, /keep verified evidence/);
assert.match(brainEcho.text, /CURRENT USER REQUEST\nfresh session/);
assert.equal((await memory.load()).recalls[`${snapshot.id}:${fresh.id}`].snapshotHash, snapshot.contentHash);
const invalidResponse = await fetch(`http://127.0.0.1:${port}/api/sessions`, { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({machineId:machine.id,cwd:workspace,agent:'echo',prompt:'must not launch',handoffId:'00000000-0000-4000-8000-000000000001'}) });
assert.equal(invalidResponse.status,201);
const invalidSession = await invalidResponse.json();
const rejected = await waitFor(async()=>{const s=await (await fetch(`http://127.0.0.1:${port}/api/sessions/${invalidSession.id}`)).json();return s.status==='failed' ? s : null;},8000,'invalid handoff rejection');
assert.ok(rejected.events.some(e=>e.kind==='error'&&e.message.includes('unknown handoff')));
assert.ok(!rejected.messages.some(m=>m.text==='Echo: must not launch'));
console.log('[acceptance] PASS: restart -> verified Brain context -> fresh agent session; invalid handoff fails closed');
for(const child of children.reverse()) child.kill('SIGTERM');
await new Promise(r=>setTimeout(r,120));

async function waitFor(fn, timeout, label){const start=Date.now();let last;while(Date.now()-start<timeout){try{last=await fn();if(last)return last;}catch(e){last=e;}await new Promise(r=>setTimeout(r,80));}throw new Error(`Timed out waiting for ${label}: ${last?.message||last||''}`)}
